"""Create tables owners, pets

Revision ID: 544d9d43bee9
Revises: 14401d14d6d1
Create Date: 2023-09-20 20:56:34.690690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544d9d43bee9'
down_revision = '14401d14d6d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
